service: whos-that-pokemon-s3gallery

frameworkVersion: ">=1.2.0 <2.0.0"

plugins:
  - serverless-python-requirements

custom:
  s3BucketName: whos-that-pokemon-gallery
  pythonRequirements:
    layer: true
    dockerizePip: false

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

package:
  include:
    - src/**

functions:
  s3gallery_maker:
    handler: src/handler.run
    events:
      - schedule: rate(90 days)
    environment:
      S3_BUCKET: ${self:custom.s3BucketName}
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

resources:
  Resources:
    GalleryBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        VersioningConfiguration:
          Status: Enabled
    GalleryBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: GalleryBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref GalleryBucket
                - /*
