---
AWSTemplateFormatVersion: '2010-09-09'
Description: The AWS CloudFormation template for this Serverless application
Parameters:
  HostedZoneName:
    Type: String
    Default: whosthatpokemon.xyz.
  GallerySiteName:
    Type: String
    Default: gallery.whosthatpokemon.xyz
  CertificateArn:
    Type: String
    Default: arn:aws:acm:us-east-1:934679804324:certificate/e9d4580c-1ff4-4836-9a7e-9a9e532be2e6
Resources:
  CloudfrontDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName:
        Ref: HostedZoneName
      RecordSets:
        - Name:
            Ref: GallerySiteName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt GalleryBucketCloudfront.DomainName
  GalleryBucketCloudfront:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - GalleryBucket
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        Comment: CloudFront to S3
        Origins:
          - DomainName: !Join
              - '.'
              - - Ref: GallerySiteName
                - s3-website-us-east-1.amazonaws.com
            Id: S3RootOrigin
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        Aliases:
          - Ref: GallerySiteName
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          Compress: false
          TargetOriginId: S3RootOrigin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn:
            Ref: CertificateArn
          SslSupportMethod: sni-only
  GalleryBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: GallerySiteName
      VersioningConfiguration:
        Status: Enabled
      WebsiteConfiguration:
        IndexDocument: /
  GalleryBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: GalleryBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: GalleryBucket
              - "/*"
  GalleryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "PokedexID"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "PokedexID"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: "PokemonGalleryTable"